FROM maven:3.8.7-amazoncorretto-17ww as buildtime

WORKDIR /build
COPY . .

RUN mvn clean package

FROM amazoncorretto:17 as runtime

WORKDIR /app

COPY --from=buildtime /build/target/*.jar /app/app.jar

ENTRYPOINT ["java","-jar","/app/app.jar"]
